//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "GameSetItem_UserSetItem", "UserSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.UserSetItem), "GameSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.GameSetItem), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "GameSetItem_UserSetItem1", "UserSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.UserSetItem), "GameSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.GameSetItem), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "HitSetItem_GameSetItem", "GameSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.GameSetItem), "HitSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.HitSetItem), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "HitSetItem_UserSetItem", "UserSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.UserSetItem), "HitSetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.HitSetItem), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationData object using the connection string found in the 'ApplicationData' section of the application configuration file.
        /// </summary>
        public ApplicationData() : base("name=ApplicationData", "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(string connectionString) : base(connectionString, "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(EntityConnection connection) : base(connection, "ApplicationData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserSetItem> UserSet
        {
            get
            {
                if ((_UserSet == null))
                {
                    _UserSet = base.CreateObjectSet<UserSetItem>("UserSet");
                }
                return _UserSet;
            }
        }
        private ObjectSet<UserSetItem> _UserSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameSetItem> GameSet
        {
            get
            {
                if ((_GameSet == null))
                {
                    _GameSet = base.CreateObjectSet<GameSetItem>("GameSet");
                }
                return _GameSet;
            }
        }
        private ObjectSet<GameSetItem> _GameSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HitSetItem> HitSet
        {
            get
            {
                if ((_HitSet == null))
                {
                    _HitSet = base.CreateObjectSet<HitSetItem>("HitSet");
                }
                return _HitSet;
            }
        }
        private ObjectSet<HitSetItem> _HitSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSet(UserSetItem userSetItem)
        {
            base.AddObject("UserSet", userSetItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameSet(GameSetItem gameSetItem)
        {
            base.AddObject("GameSet", gameSetItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HitSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHitSet(HitSetItem hitSetItem)
        {
            base.AddObject("HitSet", hitSetItem);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="GameSetItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameSetItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameSetItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="games_Users">Initial value of the Games_Users property.</param>
        /// <param name="games_Users1">Initial value of the Games_Users1 property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="isFinished">Initial value of the IsFinished property.</param>
        /// <param name="startScore">Initial value of the StartScore property.</param>
        /// <param name="p1ActualScore">Initial value of the P1ActualScore property.</param>
        /// <param name="p2ActualScore">Initial value of the P2ActualScore property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        public static GameSetItem CreateGameSetItem(global::System.Int32 id, global::System.Int32 games_Users, global::System.Int32 games_Users1, global::System.Byte[] rowVersion, global::System.Boolean isFinished, global::System.Int32 startScore, global::System.Int32 p1ActualScore, global::System.Int32 p2ActualScore, global::System.DateTime startDate)
        {
            GameSetItem gameSetItem = new GameSetItem();
            gameSetItem.Id = id;
            gameSetItem.Games_Users = games_Users;
            gameSetItem.Games_Users1 = games_Users1;
            gameSetItem.RowVersion = rowVersion;
            gameSetItem.IsFinished = isFinished;
            gameSetItem.StartScore = startScore;
            gameSetItem.P1ActualScore = p1ActualScore;
            gameSetItem.P2ActualScore = p2ActualScore;
            gameSetItem.StartDate = startDate;
            return gameSetItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Games_Users
        {
            get
            {
                return _Games_Users;
            }
            set
            {
                OnGames_UsersChanging(value);
                ReportPropertyChanging("Games_Users");
                _Games_Users = value;
                ReportPropertyChanged("Games_Users");
                OnGames_UsersChanged();
            }
        }
        private global::System.Int32 _Games_Users;
        partial void OnGames_UsersChanging(global::System.Int32 value);
        partial void OnGames_UsersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Games_Users1
        {
            get
            {
                return _Games_Users1;
            }
            set
            {
                OnGames_Users1Changing(value);
                ReportPropertyChanging("Games_Users1");
                _Games_Users1 = value;
                ReportPropertyChanged("Games_Users1");
                OnGames_Users1Changed();
            }
        }
        private global::System.Int32 _Games_Users1;
        partial void OnGames_Users1Changing(global::System.Int32 value);
        partial void OnGames_Users1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFinished
        {
            get
            {
                return _IsFinished;
            }
            set
            {
                OnIsFinishedChanging(value);
                ReportPropertyChanging("IsFinished");
                _IsFinished = value;
                ReportPropertyChanged("IsFinished");
                OnIsFinishedChanged();
            }
        }
        private global::System.Boolean _IsFinished;
        partial void OnIsFinishedChanging(global::System.Boolean value);
        partial void OnIsFinishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StartScore
        {
            get
            {
                return _StartScore;
            }
            set
            {
                OnStartScoreChanging(value);
                ReportPropertyChanging("StartScore");
                _StartScore = value;
                ReportPropertyChanged("StartScore");
                OnStartScoreChanged();
            }
        }
        private global::System.Int32 _StartScore;
        partial void OnStartScoreChanging(global::System.Int32 value);
        partial void OnStartScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 P1ActualScore
        {
            get
            {
                return _P1ActualScore;
            }
            set
            {
                OnP1ActualScoreChanging(value);
                ReportPropertyChanging("P1ActualScore");
                _P1ActualScore = value;
                ReportPropertyChanged("P1ActualScore");
                OnP1ActualScoreChanged();
            }
        }
        private global::System.Int32 _P1ActualScore;
        partial void OnP1ActualScoreChanging(global::System.Int32 value);
        partial void OnP1ActualScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 P2ActualScore
        {
            get
            {
                return _P2ActualScore;
            }
            set
            {
                OnP2ActualScoreChanging(value);
                ReportPropertyChanging("P2ActualScore");
                _P2ActualScore = value;
                ReportPropertyChanged("P2ActualScore");
                OnP2ActualScoreChanged();
            }
        }
        private global::System.Int32 _P2ActualScore;
        partial void OnP2ActualScoreChanging(global::System.Int32 value);
        partial void OnP2ActualScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = value;
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = value;
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "GameSetItem_UserSetItem", "UserSetItem")]
        public UserSetItem Player1User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "UserSetItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "UserSetItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserSetItem> Player1UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "UserSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "UserSetItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "GameSetItem_UserSetItem1", "UserSetItem")]
        public UserSetItem Player2User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "UserSetItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "UserSetItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserSetItem> Player2UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "UserSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "UserSetItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "HitSetItem_GameSetItem", "HitSetItem")]
        public EntityCollection<HitSetItem> HitsCollection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HitSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "HitSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HitSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "HitSetItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="HitSetItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HitSetItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HitSetItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="hits_Games">Initial value of the Hits_Games property.</param>
        /// <param name="hits_Users">Initial value of the Hits_Users property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="multiplicity">Initial value of the Multiplicity property.</param>
        /// <param name="turn">Initial value of the Turn property.</param>
        /// <param name="dartNumber">Initial value of the DartNumber property.</param>
        /// <param name="succesful">Initial value of the Succesful property.</param>
        /// <param name="throwDate">Initial value of the ThrowDate property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static HitSetItem CreateHitSetItem(global::System.Int32 id, global::System.Int32 hits_Games, global::System.Int32 hits_Users, global::System.Int32 value, global::System.Int32 multiplicity, global::System.Int32 turn, global::System.Int32 dartNumber, global::System.Boolean succesful, global::System.DateTime throwDate, global::System.Byte[] rowVersion)
        {
            HitSetItem hitSetItem = new HitSetItem();
            hitSetItem.Id = id;
            hitSetItem.Hits_Games = hits_Games;
            hitSetItem.Hits_Users = hits_Users;
            hitSetItem.Value = value;
            hitSetItem.Multiplicity = multiplicity;
            hitSetItem.Turn = turn;
            hitSetItem.DartNumber = dartNumber;
            hitSetItem.Succesful = succesful;
            hitSetItem.ThrowDate = throwDate;
            hitSetItem.RowVersion = rowVersion;
            return hitSetItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hits_Games
        {
            get
            {
                return _Hits_Games;
            }
            set
            {
                OnHits_GamesChanging(value);
                ReportPropertyChanging("Hits_Games");
                _Hits_Games = value;
                ReportPropertyChanged("Hits_Games");
                OnHits_GamesChanged();
            }
        }
        private global::System.Int32 _Hits_Games;
        partial void OnHits_GamesChanging(global::System.Int32 value);
        partial void OnHits_GamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hits_Users
        {
            get
            {
                return _Hits_Users;
            }
            set
            {
                OnHits_UsersChanging(value);
                ReportPropertyChanging("Hits_Users");
                _Hits_Users = value;
                ReportPropertyChanged("Hits_Users");
                OnHits_UsersChanged();
            }
        }
        private global::System.Int32 _Hits_Users;
        partial void OnHits_UsersChanging(global::System.Int32 value);
        partial void OnHits_UsersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = value;
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int32 _Value;
        partial void OnValueChanging(global::System.Int32 value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Multiplicity
        {
            get
            {
                return _Multiplicity;
            }
            set
            {
                OnMultiplicityChanging(value);
                ReportPropertyChanging("Multiplicity");
                _Multiplicity = value;
                ReportPropertyChanged("Multiplicity");
                OnMultiplicityChanged();
            }
        }
        private global::System.Int32 _Multiplicity;
        partial void OnMultiplicityChanging(global::System.Int32 value);
        partial void OnMultiplicityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Turn
        {
            get
            {
                return _Turn;
            }
            set
            {
                OnTurnChanging(value);
                ReportPropertyChanging("Turn");
                _Turn = value;
                ReportPropertyChanged("Turn");
                OnTurnChanged();
            }
        }
        private global::System.Int32 _Turn;
        partial void OnTurnChanging(global::System.Int32 value);
        partial void OnTurnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DartNumber
        {
            get
            {
                return _DartNumber;
            }
            set
            {
                OnDartNumberChanging(value);
                ReportPropertyChanging("DartNumber");
                _DartNumber = value;
                ReportPropertyChanged("DartNumber");
                OnDartNumberChanged();
            }
        }
        private global::System.Int32 _DartNumber;
        partial void OnDartNumberChanging(global::System.Int32 value);
        partial void OnDartNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Succesful
        {
            get
            {
                return _Succesful;
            }
            set
            {
                OnSuccesfulChanging(value);
                ReportPropertyChanging("Succesful");
                _Succesful = value;
                ReportPropertyChanged("Succesful");
                OnSuccesfulChanged();
            }
        }
        private global::System.Boolean _Succesful;
        partial void OnSuccesfulChanging(global::System.Boolean value);
        partial void OnSuccesfulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ThrowDate
        {
            get
            {
                return _ThrowDate;
            }
            set
            {
                OnThrowDateChanging(value);
                ReportPropertyChanging("ThrowDate");
                _ThrowDate = value;
                ReportPropertyChanged("ThrowDate");
                OnThrowDateChanged();
            }
        }
        private global::System.DateTime _ThrowDate;
        partial void OnThrowDateChanging(global::System.DateTime value);
        partial void OnThrowDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "HitSetItem_GameSetItem", "GameSetItem")]
        public GameSetItem Game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "GameSetItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "GameSetItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GameSetItem> GameReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "GameSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GameSetItem>("LightSwitchApplication.HitSetItem_GameSetItem", "GameSetItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "HitSetItem_UserSetItem", "UserSetItem")]
        public UserSetItem Player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "UserSetItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "UserSetItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserSetItem> PlayerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "UserSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "UserSetItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="UserSetItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserSetItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserSetItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="win">Initial value of the Win property.</param>
        /// <param name="lose">Initial value of the Lose property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static UserSetItem CreateUserSetItem(global::System.Int32 id, global::System.String name, global::System.Int32 win, global::System.Int32 lose, global::System.Byte[] rowVersion)
        {
            UserSetItem userSetItem = new UserSetItem();
            userSetItem.Id = id;
            userSetItem.Name = name;
            userSetItem.Win = win;
            userSetItem.Lose = lose;
            userSetItem.RowVersion = rowVersion;
            return userSetItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Win
        {
            get
            {
                return _Win;
            }
            set
            {
                OnWinChanging(value);
                ReportPropertyChanging("Win");
                _Win = value;
                ReportPropertyChanged("Win");
                OnWinChanged();
            }
        }
        private global::System.Int32 _Win;
        partial void OnWinChanging(global::System.Int32 value);
        partial void OnWinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lose
        {
            get
            {
                return _Lose;
            }
            set
            {
                OnLoseChanging(value);
                ReportPropertyChanging("Lose");
                _Lose = value;
                ReportPropertyChanged("Lose");
                OnLoseChanged();
            }
        }
        private global::System.Int32 _Lose;
        partial void OnLoseChanging(global::System.Int32 value);
        partial void OnLoseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "GameSetItem_UserSetItem", "GameSetItem")]
        public EntityCollection<GameSetItem> GamesAsPlayer1Collection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GameSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "GameSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GameSetItem>("LightSwitchApplication.GameSetItem_UserSetItem", "GameSetItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "GameSetItem_UserSetItem1", "GameSetItem")]
        public EntityCollection<GameSetItem> GamesAsPlayer2Collection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GameSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "GameSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GameSetItem>("LightSwitchApplication.GameSetItem_UserSetItem1", "GameSetItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "HitSetItem_UserSetItem", "HitSetItem")]
        public EntityCollection<HitSetItem> HitsCollection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HitSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "HitSetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HitSetItem>("LightSwitchApplication.HitSetItem_UserSetItem", "HitSetItem", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
