//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Inserting(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Inserted(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Updating(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Updated(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Deleting(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Deleted(global::LightSwitchApplication.UserSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Validate(global::LightSwitchApplication.UserSetItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.UserSetItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Inserting(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Inserted(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Updating(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Updated(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Deleting(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Deleted(global::LightSwitchApplication.GameSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Validate(global::LightSwitchApplication.GameSetItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GameSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.GameSetItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Inserting(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Inserted(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Updating(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Updated(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Deleting(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Deleted(global::LightSwitchApplication.HitSetItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Validate(global::LightSwitchApplication.HitSetItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HitSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HitSetItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.UserSetItem>
                __UserSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.UserSetItem>(
                    "UserSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__UserSet_Filter);
            private static bool __UserSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.UserSet_CanInsert(ref result);
                return result;
            }
            private static bool __UserSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.UserSet_CanUpdate(ref result);
                return result;
            }
            private static bool __UserSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.UserSet_CanDelete(ref result);
                return result;
            }
            private static bool __UserSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.UserSet_CanRead(ref result);
                return result;
            }
            private static void __UserSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Inserting(e);
            }
            private static void __UserSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Inserted(e);
            }
            private static void __UserSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Updating(e);
            }
            private static void __UserSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Updated(e);
            }
            private static void __UserSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Deleting(e);
            }
            private static void __UserSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e)
            {
                d.UserSet_Deleted(e);
            }
            private static void __UserSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.UserSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.UserSetItem, bool>> __UserSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.UserSetItem, bool>> filter = null;
                d.UserSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.GameSetItem>
                __GameSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.GameSetItem>(
                    "GameSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__GameSet_Filter);
            private static bool __GameSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.GameSet_CanInsert(ref result);
                return result;
            }
            private static bool __GameSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.GameSet_CanUpdate(ref result);
                return result;
            }
            private static bool __GameSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.GameSet_CanDelete(ref result);
                return result;
            }
            private static bool __GameSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.GameSet_CanRead(ref result);
                return result;
            }
            private static void __GameSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Inserting(e);
            }
            private static void __GameSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Inserted(e);
            }
            private static void __GameSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Updating(e);
            }
            private static void __GameSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Updated(e);
            }
            private static void __GameSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Deleting(e);
            }
            private static void __GameSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e)
            {
                d.GameSet_Deleted(e);
            }
            private static void __GameSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.GameSetItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.GameSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.GameSetItem, bool>> __GameSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.GameSetItem, bool>> filter = null;
                d.GameSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.HitSetItem>
                __HitSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.HitSetItem>(
                    "HitSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HitSet_Filter);
            private static bool __HitSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HitSet_CanInsert(ref result);
                return result;
            }
            private static bool __HitSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HitSet_CanUpdate(ref result);
                return result;
            }
            private static bool __HitSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HitSet_CanDelete(ref result);
                return result;
            }
            private static bool __HitSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HitSet_CanRead(ref result);
                return result;
            }
            private static void __HitSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Inserting(e);
            }
            private static void __HitSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Inserted(e);
            }
            private static void __HitSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Updating(e);
            }
            private static void __HitSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Updated(e);
            }
            private static void __HitSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Deleting(e);
            }
            private static void __HitSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e)
            {
                d.HitSet_Deleted(e);
            }
            private static void __HitSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HitSetItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.HitSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HitSetItem, bool>> __HitSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HitSetItem, bool>> filter = null;
                d.HitSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
