

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class UserSetItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UserSetItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserSetItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserSetItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserSetItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UserSetItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSetItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserSetItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.UserSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.UserSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Win
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Win);
            }
            set
            {
                global::LightSwitchApplication.UserSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Win, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Win_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Win_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Win_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Lose
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Lose);
            }
            set
            {
                global::LightSwitchApplication.UserSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Lose, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lose_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lose_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lose_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.UserSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.GameSetItem> GamesAsPlayer1Collection
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer1Collection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.GameSetItem> GamesAsPlayer1CollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer1Collection);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.GameSetItem> GamesAsPlayer2Collection
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer2Collection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.GameSetItem> GamesAsPlayer2CollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer2Collection);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.HitSetItem> HitsCollection
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.HitsCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.HitSetItem> HitsCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.UserSetItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.HitsCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UserSetItem,
                global::LightSwitchApplication.UserSetItem.DetailsClass,
                global::LightSwitchApplication.UserSetItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>.Entry
                __UserSetItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.UserSetItem.DetailsClass.__UserSetItem_CreateNew,
                    global::LightSwitchApplication.UserSetItem.DetailsClass.__UserSetItem_Created,
                    global::LightSwitchApplication.UserSetItem.DetailsClass.__UserSetItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UserSetItem __UserSetItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserSetItem> es)
            {
                return new global::LightSwitchApplication.UserSetItem(es);
            }
            private static void __UserSetItem_Created(global::LightSwitchApplication.UserSetItem e)
            {
                e.UserSetItem_Created();
            }
            private static bool __UserSetItem_AllowSaveWithErrors(global::LightSwitchApplication.UserSetItem e)
            {
                bool result = false;
                e.UserSetItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int> Win
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Win) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int> Lose
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Lose) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem> GamesAsPlayer1Collection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer1Collection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem> GamesAsPlayer2Collection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer2Collection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem> HitsCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.HitsCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Name { get; set; }
                new int Win { get; set; }
                new int Lose { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable GamesAsPlayer1Collection { get; }
                new global::System.Collections.IEnumerable GamesAsPlayer2Collection { get; }
                new global::System.Collections.IEnumerable HitsCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry
                    Win = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry(
                        "Win",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_GetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_SetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Win_OnValueChanged);
                private static void _Win_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Win, sf);
                }
                private static bool _Win_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Win_IsReadOnly(ref result);
                    return result;
                }
                private static void _Win_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Win_Validate(r);
                }
                private static int _Win_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Win;
                }
                private static void _Win_SetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Win = v;
                }
                private static void _Win_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Win_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry
                    Lose = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Entry(
                        "Lose",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_GetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_SetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Lose_OnValueChanged);
                private static void _Lose_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Lose, sf);
                }
                private static bool _Lose_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Lose_IsReadOnly(ref result);
                    return result;
                }
                private static void _Lose_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Lose_Validate(r);
                }
                private static int _Lose_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Lose;
                }
                private static void _Lose_SetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Lose = v;
                }
                private static void _Lose_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Lose_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.UserSetItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.UserSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.UserSetItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.UserSetItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Entry
                    GamesAsPlayer1Collection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Entry(
                        "GamesAsPlayer1Collection",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer1Collection_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer1Collection_GetReferencedEntities,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer1Collection_GetEntityCollection);
                private static void _GamesAsPlayer1Collection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._GamesAsPlayer1Collection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.GameSetItem> _GamesAsPlayer1Collection_GetReferencedEntities(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.GameSetItem, global::LightSwitchApplication.GameSetItem.DetailsClass>(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer1Collection, ref d._GamesAsPlayer1Collection);
                }
                private static global::System.Collections.IEnumerable _GamesAsPlayer1Collection_GetEntityCollection(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.GamesAsPlayer1Collection;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Entry
                    GamesAsPlayer2Collection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Entry(
                        "GamesAsPlayer2Collection",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer2Collection_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer2Collection_GetReferencedEntities,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._GamesAsPlayer2Collection_GetEntityCollection);
                private static void _GamesAsPlayer2Collection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._GamesAsPlayer2Collection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.GameSetItem> _GamesAsPlayer2Collection_GetReferencedEntities(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.GameSetItem, global::LightSwitchApplication.GameSetItem.DetailsClass>(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.GamesAsPlayer2Collection, ref d._GamesAsPlayer2Collection);
                }
                private static global::System.Collections.IEnumerable _GamesAsPlayer2Collection_GetEntityCollection(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.GamesAsPlayer2Collection;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem>.Entry
                    HitsCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem>.Entry(
                        "HitsCollection",
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._HitsCollection_Stub,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._HitsCollection_GetReferencedEntities,
                        global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties._HitsCollection_GetEntityCollection);
                private static void _HitsCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem>.Data> c, global::LightSwitchApplication.UserSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._HitsCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.HitSetItem> _HitsCollection_GetReferencedEntities(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.HitSetItem, global::LightSwitchApplication.HitSetItem.DetailsClass>(global::LightSwitchApplication.UserSetItem.DetailsClass.PropertySetProperties.HitsCollection, ref d._HitsCollection);
                }
                private static global::System.Collections.IEnumerable _HitsCollection_GetEntityCollection(global::LightSwitchApplication.UserSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.HitsCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data _Win;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, int>.Data _Lose;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Data _GamesAsPlayer1Collection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.GameSetItem>.Data _GamesAsPlayer2Collection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserSetItem, global::LightSwitchApplication.UserSetItem.DetailsClass, global::LightSwitchApplication.HitSetItem>.Data _HitsCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
