// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/AddEditGame.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/AddEditUser.lsml.js\"></script>");
